import { test } from "node:test";
import assert from "node:assert/strict";
import {
  parseReviewerMarker,
  resolveSource,
  profileFor,
  TRUSTED_REVIEWERS,
} from "../src/reviewers.ts";

test("parseReviewerMarker extracts the reviewer name from the Generated-by footer", () => {
  assert.equal(
    parseReviewerMarker("...body...\n> Generated by [CARE PR Reviewer](https://x) for #16632 · opus50"),
    "CARE PR Reviewer",
  );
  assert.equal(
    parseReviewerMarker("Generated by [Grumpy PR Reviewer](https://y) for #1"),
    "Grumpy PR Reviewer",
  );
  assert.equal(parseReviewerMarker("no marker here"), undefined);
  assert.equal(parseReviewerMarker(""), undefined);
  assert.equal(parseReviewerMarker(undefined), undefined);
});

test("resolveSource: a body marker names our reviewer even under the github-actions login", () => {
  assert.equal(
    resolveSource("github-actions[bot]", "CARE PR Reviewer"),
    "CARE PR Reviewer",
  );
  assert.equal(
    resolveSource("github-actions[bot]", "Grumpy PR Reviewer"),
    "Grumpy PR Reviewer",
  );
});

test("resolveSource: github-actions[bot] with NO marker is not review content (excluded)", () => {
  // Playwright results / deploy-status comments post under the same login with no marker.
  assert.equal(resolveSource("github-actions[bot]", undefined), undefined);
});

test("resolveSource: third-party bots resolve by login", () => {
  assert.equal(resolveSource("coderabbitai[bot]"), "CodeRabbit");
  assert.equal(resolveSource("greptile-apps[bot]"), "Greptile");
  assert.equal(resolveSource("Copilot"), "Copilot");
  assert.equal(resolveSource("copilot-pull-request-reviewer[bot]"), "Copilot");
  assert.equal(resolveSource("chatgpt-codex-connector[bot]"), "Codex");
});

test("resolveSource: an unknown bot keeps its login; a human is excluded", () => {
  assert.equal(
    resolveSource("cloudflare-workers-and-pages[bot]"),
    "cloudflare-workers-and-pages[bot]",
  );
  assert.equal(resolveSource("jacobjeevan"), undefined);
});

test("profileFor: trusted reviewers are unbounded findings channels", () => {
  for (const src of TRUSTED_REVIEWERS) {
    const p = profileFor(src);
    assert.equal(p.trusted, true);
    assert.equal(p.maxChars, undefined); // unbounded — §11 D1
    assert.equal(p.maxLines, undefined);
    assert.equal(p.bodyIsFindings, true);
  }
});

test("profileFor: unknown / third-party sources get the clamped untrusted default", () => {
  for (const src of ["CodeRabbit", "Greptile", "Copilot", "SomeNewBot"]) {
    const p = profileFor(src);
    assert.equal(p.trusted, false);
    assert.equal(p.maxChars, 600);
    assert.equal(p.maxLines, 8);
    assert.equal(p.bodyIsFindings, false);
  }
});
