// feedback.ts — pre-digest PR bot feedback for Step 6a, ported from collect-feedback.sh onto the
// GitHubApi boundary (no gh, no jq, no base64/awk/sed pipeline). Fetches inline + summary bot
// comments, strips the CodeRabbit/Greptile HTML chrome, groups inline comments by file+line, tags
// [resolved] threads, and renders a compact digest so 6a starts from judgment, not parsing.

import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { GitHubApi, PrComment, PrReview } from "./github.js";
import { parseReviewerMarker, profileFor, resolveSource } from "./reviewers.js";

const BOT_RE = /\[bot\]|Copilot|coderabbit|greptile|codex/i;
export const isBot = (login: string): boolean => BOT_RE.test(login);

const CHROME_RE = /^\s*(prompt for ai agents|walkthrough|📝|🧩|<summary)/i;
const TABLE_RULE_RE = /^\s*\|?\s*[-:|\s]+\s*\|?\s*$/;

/**
 * Strip bot padding to the human-readable core: drop <details> blocks (collapsible chrome + the
 * "prompt for AI agents" blobs), HTML comments/tags, image refs, table rules and chrome lines;
 * keep at most `maxLines` non-empty lines; cap at `maxChars`. Pure — the awk/sed pipeline as string
 * ops. The budget defaults to 600 chars / 8 lines (the chrome-defanging default for third-party
 * bots); trusted reviewers pass an unbounded budget so their fix suggestions survive (§11 D1).
 */
export function trimBody(
  body: string,
  budget?: { maxChars?: number; maxLines?: number },
): string {
  const maxChars = budget?.maxChars ?? 600;
  const maxLines = budget?.maxLines ?? 8;
  const out: string[] = [];
  let detail = 0;
  let kept = 0;
  let lastBlank = false;

  for (const raw of body.split("\n")) {
    if (/<details/i.test(raw)) {
      detail++;
      continue;
    }
    if (/<\/details>/i.test(raw)) {
      if (detail > 0) detail--;
      continue;
    }
    if (detail > 0) continue;

    const cleaned = raw
      .replace(/<!--.*?-->/g, "")
      .replace(/!\[[^\]]*\]\([^)]*\)/g, "") // images
      .replace(/<[^>]+>/g, ""); // remaining tags

    if (TABLE_RULE_RE.test(cleaned)) continue;
    if (CHROME_RE.test(cleaned)) continue;

    if (cleaned.trim().length === 0) {
      if (!lastBlank && kept > 0) out.push("");
      lastBlank = true;
      continue;
    }
    out.push(cleaned);
    lastBlank = false;
    if (++kept >= maxLines) break;
  }

  return out.join("\n").slice(0, maxChars).trimEnd();
}

/**
 * Opt-in digest extensions (PLAN-pr-salvage §3.0). EVERY field defaults to today's behavior, so the
 * loop's digest is byte-identical unless a caller (the standalone `--pr` salvage path) opts in. The
 * loop passes none of these; a snapshot test pins the default output.
 */
export interface FeedbackOptions {
  reviewBodies?: boolean; // C0a — render `## Review summaries` from review bodies (default off)
  unanchored?: boolean; // C0a — parse "could not be inline-anchored" findings (default off)
  attributeSources?: boolean; // C0b — resolve real reviewer names, per-source trim budgets (default off)
}

export interface FeedbackInputs {
  pr: number;
  reviewComments: PrComment[]; // inline (have path/line/id)
  issueComments: PrComment[]; // summary/top-level (have id)
  resolvedIds: number[];
  reviews?: PrReview[]; // review submissions (bodies + ids) — needed for reviewBodies / attributeSources
  /** Thread IDs addressed by the implementer in prior rounds (from addressed-threads.json). */
  addressedThreads?: { threadId: number; round: number }[];
  options?: FeedbackOptions;
  now?: string;
}

/** A finding parsed from a review body's "Comments that could not be inline-anchored" section —
 *  carries a path/line but no thread (nothing to reply to / resolve). Salvage-only (§3 D3). */
export interface UnanchoredFinding {
  source: string;
  path: string;
  line?: number;
  body: string;
}

/** Render the feedback.md digest (pure). With `options` unset every code path below reduces to the
 *  original loop digest — identity is pinned by the snapshot test (PLAN-pr-salvage §3.0). */
export function renderFeedback(inp: FeedbackInputs): {
  markdown: string;
  count: number;
} {
  const opts = inp.options ?? {};
  const reviews = inp.reviews ?? [];
  const resolved = new Set(inp.resolvedIds);
  // reviewId → parsed `Generated by [...]` marker, for attributing inline comments to their reviewer.
  const markerByReviewId = new Map<number, string | undefined>();
  for (const r of reviews) markerByReviewId.set(r.id, parseReviewerMarker(r.body));

  // ── Attribution seam (all no-ops when attributeSources is off) ──────────────────────────────────
  // The marker for a comment: inline → its parent review's body; issue → its own body.
  const markerFor = (c: PrComment, section: "inline" | "issue") =>
    section === "inline"
      ? c.reviewId !== undefined
        ? markerByReviewId.get(c.reviewId)
        : undefined
      : parseReviewerMarker(c.body);
  const displaySource = (c: PrComment, section: "inline" | "issue") =>
    opts.attributeSources
      ? (resolveSource(c.user, markerFor(c, section)) ?? c.user)
      : c.user;
  const include = (c: PrComment, section: "inline" | "issue") =>
    opts.attributeSources
      ? resolveSource(c.user, markerFor(c, section)) !== undefined
      : isBot(c.user);
  const budgetFor = (c: PrComment, section: "inline" | "issue") => {
    if (!opts.attributeSources) return undefined; // default 600/8
    const src = resolveSource(c.user, markerFor(c, section));
    if (!src) return undefined;
    const p = profileFor(src);
    // A profile's undefined budget means UNBOUNDED — map it to Infinity, not trimBody's 600/8 default.
    return { maxChars: p.maxChars ?? Infinity, maxLines: p.maxLines ?? Infinity };
  };

  // Map from threadId → round for threads addressed by the implementer in prior rounds.
  // Tagged [addressed round N] so the triager declines re-litigating already-fixed findings.
  const addressedMap = new Map<number, number>();
  for (const { threadId, round } of inp.addressedThreads ?? []) {
    // Keep the earliest round (first time addressed) for a stable label.
    if (!addressedMap.has(threadId)) addressedMap.set(threadId, round);
  }
  const now = inp.now ?? new Date().toISOString().replace(/\.\d+Z$/, "Z");
  const L: string[] = [
    `# PR #${inp.pr} — pre-digested bot feedback   (${now})`,
    "# (author · path:line · thread-id · trimmed body) — grouped by file+line; every comment",
    "# kept (co-located bots each keep their thread id). [resolved] threads are skippable.",
    "# Source of truth is the live thread; this is the triage starting point (see the care-triager skill).",
    "",
  ];
  let count = 0;

  // 1) Inline comments — actionable (path + line + resolvable thread id). Group by path:line,
  //    sorted by path, then line, then id; ALL bot comments kept (co-located threads each need a
  //    verdict + reply for the Step-7 reply-to-every-thread exit).
  L.push("## Inline comments");
  const inline = inp.reviewComments
    .filter((c) => include(c, "inline"))
    .sort(
      (a, b) =>
        (a.path ?? "").localeCompare(b.path ?? "") ||
        (a.line ?? 0) - (b.line ?? 0) ||
        (a.id ?? 0) - (b.id ?? 0),
    );
  let prevLoc = "";
  for (const c of inline) {
    const loc = `${c.path ?? "-"}:${c.line ?? "-"}`;
    if (loc !== prevLoc) {
      L.push(`- \`${loc}\``);
      prevLoc = loc;
    }
    const tag =
      c.id !== undefined && resolved.has(c.id)
        ? " [resolved]"
        : c.id !== undefined && addressedMap.has(c.id)
          ? ` [addressed round ${addressedMap.get(c.id)}]`
          : "";
    L.push(`  - **${displaySource(c, "inline")}** (thread ${c.id ?? "-"})${tag}`);
    L.push(indent(trimBody(c.body, budgetFor(c, "inline")), 6));
    L.push("");
    count++;
  }

  // 2) Summary / top-level bot comments (Greptile summary, CodeRabbit walkthrough, …).
  L.push("## Summary comments");
  for (const c of inp.issueComments.filter((c) => include(c, "issue"))) {
    L.push(`- **${displaySource(c, "issue")}** (comment ${c.id ?? "-"})`);
    L.push(indent(trimBody(c.body, budgetFor(c, "issue")), 4));
    L.push("");
    count++;
  }

  // 3) Review summaries — the review BODIES the two earlier sections never fetch (C0a). Latest 2 per
  //    resolved source, newest first, SHA-labeled (these are DELTA reviews). Opt-in.
  if (opts.reviewBodies) {
    const summaries = selectReviewBodies(reviews);
    if (summaries.length > 0) {
      L.push("## Review summaries");
      L.push(
        "# latest review bodies per reviewer (delta reviews — newest first). Context, not threads.",
      );
      for (const s of summaries) {
        const p = profileFor(s.source);
        L.push(
          `- **${s.source}** (${s.commitId.slice(0, 9)} · ${s.submittedAt})`,
        );
        L.push(
          indent(
            trimBody(s.body, {
              maxChars: p.maxChars ?? Infinity,
              maxLines: p.maxLines ?? Infinity,
            }),
            4,
          ),
        );
        L.push("");
        count++;
      }
    }
  }

  // 4) Unanchored findings — real path:line findings that could not be inline-anchored, parsed from
  //    the review bodies (C0a). No thread ⇒ addressable but never reply/resolve (§3 D3). Opt-in.
  if (opts.unanchored) {
    const findings = parseUnanchoredFindings(reviews);
    if (findings.length > 0) {
      L.push("## Unanchored findings");
      L.push(
        "# path:line findings with NO thread — addressable, but no reply/resolve target.",
      );
      for (const f of findings) {
        const loc = f.line !== undefined ? `${f.path}:${f.line}` : f.path;
        L.push(`- \`${loc}\` — **${f.source}**`);
        if (f.body.trim()) L.push(indent(trimBody(f.body), 4));
        L.push("");
        count++;
      }
    }
  }

  return { markdown: L.join("\n") + "\n", count };
}

/** Latest 2 review bodies per resolved source, newest first (PLAN-pr-salvage §11 D2). Reviews with
 *  no body or that resolve to no reviewer (deploy previews, etc.) are dropped. Pure. */
export function selectReviewBodies(
  reviews: PrReview[],
): { source: string; body: string; commitId: string; submittedAt: string }[] {
  const bySource = new Map<
    string,
    { source: string; body: string; commitId: string; submittedAt: string }[]
  >();
  for (const r of reviews) {
    if (!r.body?.trim()) continue;
    const src = resolveSource(r.user, parseReviewerMarker(r.body));
    if (!src) continue;
    const bucket = bySource.get(src) ?? [];
    bucket.push({
      source: src,
      body: r.body,
      commitId: r.commitId,
      submittedAt: r.submittedAt,
    });
    bySource.set(src, bucket);
  }
  const out: {
    source: string;
    body: string;
    commitId: string;
    submittedAt: string;
  }[] = [];
  for (const bucket of bySource.values()) {
    bucket.sort((a, b) => b.submittedAt.localeCompare(a.submittedAt)); // newest first
    out.push(...bucket.slice(0, 2));
  }
  // Stable overall order: by source, then newest-first within source.
  out.sort(
    (a, b) =>
      a.source.localeCompare(b.source) ||
      b.submittedAt.localeCompare(a.submittedAt),
  );
  return out;
}

const UNANCHORED_HEADING =
  /^#{0,4}\s*Comments that could not be inline-anchored/im;
const PATH_LINE = /([\w./-]+\.(?:ts|tsx|js|jsx|css|json|md)):(\d+)/i;
// Our reviewers emit each unanchored finding as a <details> block: the summary is the path:line, the
// inner text is the prose. `<summary>` may also carry the prose after the path (some rounds do both).
const DETAILS_BLOCK =
  /<details>\s*<summary>([\s\S]*?)<\/summary>([\s\S]*?)<\/details>/gi;

/** Minimal HTML/entity cleanup for prose lifted from a review body (not a full sanitizer). */
function stripHtml(s: string): string {
  return s
    .replace(/<[^>]+>/g, "")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/\s+\n/g, "\n")
    .trim();
}

/** Parse the "Comments that could not be inline-anchored" section from each resolved review body
 *  into path:line findings (PLAN-pr-salvage §6 C0a). Handles the `<details>` format our reviewers
 *  emit, falling back to line-scanning. Deduped by source+path:line. Pure. */
export function parseUnanchoredFindings(
  reviews: PrReview[],
): UnanchoredFinding[] {
  const out: UnanchoredFinding[] = [];
  const seen = new Set<string>();
  const add = (src: string, path: string, line: number, body: string) => {
    const key = `${src}::${path}:${line}`;
    if (seen.has(key)) return;
    seen.add(key);
    out.push({ source: src, path, line, body: body.trim() });
  };
  for (const r of reviews) {
    const src = resolveSource(r.user, parseReviewerMarker(r.body));
    if (!src) continue;
    const body = r.body ?? "";
    const idx = body.search(UNANCHORED_HEADING);
    if (idx < 0) continue;
    const section = body.slice(idx);

    let matched = false;
    for (const m of section.matchAll(DETAILS_BLOCK)) {
      const loc = PATH_LINE.exec(m[1]);
      if (!loc) continue;
      matched = true;
      // Prose = the block body, plus any summary text after the path:line.
      const summaryProse = m[1].replace(PATH_LINE, "").trim();
      const prose = stripHtml([summaryProse, m[2]].filter(Boolean).join(" "));
      add(src, loc[1], Number(loc[2]), prose);
    }
    if (matched) continue;

    // Fallback: plain list — one `… path:line … prose` per line.
    for (const line of section.split("\n").slice(1)) {
      const loc = PATH_LINE.exec(line);
      if (!loc) continue;
      add(src, loc[1], Number(loc[2]), stripHtml(line));
    }
  }
  return out;
}

/** Group the rendered feedback.md into per-FILE clusters: the "## Inline comments" section is emitted
 *  grouped by `path:line`, and the triager pre-reads each cluster's file into its prompt. Returns the
 *  per-file blocks (verbatim markdown) plus the file-less "## Summary comments" body (bot
 *  walkthroughs). Pure — parses OUR own stable `renderFeedback` format, not arbitrary markdown. */
export function parseFeedbackClusters(md: string): {
  clusters: { file: string; text: string }[];
  summary: string;
} {
  const lines = md.split("\n");
  const inlineIdx = lines.findIndex((l) => /^##\s+Inline comments/i.test(l));
  const summaryIdx = lines.findIndex((l) => /^##\s+Summary comments/i.test(l));
  const inline =
    inlineIdx >= 0
      ? lines.slice(inlineIdx + 1, summaryIdx >= 0 ? summaryIdx : undefined)
      : [];
  const summary =
    summaryIdx >= 0
      ? lines
          .slice(summaryIdx + 1)
          .join("\n")
          .trim()
      : "";

  // A location header looks like: - `src/foo/Bar.tsx:169`  (line may be a number or "-"). The file is
  // everything before the final `:<line>` — greedy `.+` backtracks to the last colon.
  const headerRe = /^- `(.+):(?:\d+|-)`\s*$/;
  const byFile = new Map<string, string[]>();
  let curFile = "";
  for (const l of inline) {
    const m = headerRe.exec(l);
    if (m) curFile = m[1];
    if (curFile) {
      const bucket = byFile.get(curFile) ?? [];
      bucket.push(l);
      byFile.set(curFile, bucket);
    }
  }
  const clusters = [...byFile.entries()].map(([file, ls]) => ({
    file,
    text: ls.join("\n").trim(),
  }));
  return { clusters, summary };
}

function indent(text: string, n: number): string {
  const pad = " ".repeat(n);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

/** Fetch + render + write feedback.md. CI checks and our own /care-review findings are NOT here.
 *  `options` are the opt-in digest extensions (§3.0) — the loop passes none (byte-identical digest);
 *  the salvage `--pr` path passes all three. Review bodies are fetched only when an option needs them,
 *  so the loop makes no extra GitHub call. */
export async function collectFeedback(
  gh: GitHubApi,
  opts: { pr: number; runDir?: string; options?: FeedbackOptions },
): Promise<{ markdown: string; count: number }> {
  const needReviews =
    !!opts.options?.reviewBodies ||
    !!opts.options?.unanchored ||
    !!opts.options?.attributeSources;
  const [reviewComments, issueComments, resolvedIds, reviews] =
    await Promise.all([
      gh.listReviewComments(opts.pr),
      gh.listIssueComments(opts.pr),
      gh.listResolvedReviewCommentIds(opts.pr),
      needReviews ? gh.listReviews(opts.pr) : Promise.resolve([]),
    ]);
  // Load prior-round addressed thread IDs from run dir to annotate re-surfaced threads.
  let addressedThreads: { threadId: number; round: number }[] = [];
  if (opts.runDir) {
    try {
      addressedThreads = JSON.parse(
        readFileSync(join(opts.runDir, "addressed-threads.json"), "utf8"),
      );
    } catch {
      /* not found = first round, no prior addresses */
    }
  }
  const rendered = renderFeedback({
    pr: opts.pr,
    reviewComments,
    issueComments,
    resolvedIds,
    reviews,
    addressedThreads,
    options: opts.options,
  });
  if (opts.runDir) {
    mkdirSync(opts.runDir, { recursive: true });
    writeFileSync(join(opts.runDir, "feedback.md"), rendered.markdown);
  }
  return rendered;
}
