// reviewers.ts — reviewer identity + per-source digest policy (PLAN-pr-salvage §6 C0b/C0c).
//
// The problem: both our CI reviewers (CARE PR Reviewer, Grumpy PR Reviewer) post as
// `github-actions[bot]`, as do unrelated CI comments (Playwright results, Cloudflare previews). The
// login is NOT an identity. Resolution:
//   1. A review BODY carries a `Generated by [<Name>](url)` marker → that reviewer.
//   2. An inline comment joins to its parent review via `pull_request_review_id` → inherits (1).
//   3. Third-party bots (CodeRabbit/Greptile/Copilot/Codex) are identified by login, as before.
//   4. Anything under `github-actions[bot]` with no marker is NOT review content → excluded.
//
// The per-source profile then controls the trim budget: our own reviewers are dense signal and are
// left unbounded (HTML-stripped only, §11 D1); third-party bots keep the 600/8 chrome-defanging
// budget. The budget is a DISPLAY policy, never a trust policy — HTML stripping and the triage
// rubric's injection guard apply to trusted sources unchanged.

/** Per-source digest policy. `maxChars`/`maxLines` undefined ⇒ unbounded (trusted only). */
export interface ReviewerProfile {
  source: string; // resolved identity (§6 C0b), not the raw login
  trusted: boolean; // our own reviewers
  maxChars?: number; // trimBody budget; undefined = unbounded
  maxLines?: number;
  bodyIsFindings: boolean; // is the review body a findings channel, or boilerplate?
}

/** Our own CI reviewers, identified by their review-body `Generated by [...]` marker. Extend this
 *  set when a new trusted reviewer is added — one line. Unknown sources default to untrusted. */
export const TRUSTED_REVIEWERS = new Set(["CARE PR Reviewer", "Grumpy PR Reviewer"]);

/** Third-party bots, identified by login substring (their bodies are chrome, not findings). */
const THIRD_PARTY: { match: RegExp; source: string }[] = [
  { match: /coderabbit/i, source: "CodeRabbit" },
  { match: /greptile/i, source: "Greptile" },
  { match: /copilot/i, source: "Copilot" },
  { match: /codex|chatgpt-codex-connector/i, source: "Codex" },
];

const MARKER_RE = /Generated by \[([^\]]+?)\]/i;

/** The reviewer name from a review body's `Generated by [<Name>](url)` marker, or undefined. */
export function parseReviewerMarker(body: string | undefined): string | undefined {
  if (!body) return undefined;
  const m = MARKER_RE.exec(body);
  return m ? m[1].trim() : undefined;
}

/**
 * Resolve a comment/review to its reviewer identity, or `undefined` if it is not review content.
 * `markerName` is the parsed marker from the item's own body (a review) or its parent review's body
 * (an inline comment). Third-party bots resolve by login; a `github-actions[bot]` with no marker is
 * excluded (Playwright results, deploy previews); other bot logins keep their login as source.
 */
export function resolveSource(
  login: string,
  markerName?: string,
): string | undefined {
  if (markerName) return markerName; // trusted reviewer (from a body marker)
  for (const tp of THIRD_PARTY) if (tp.match.test(login)) return tp.source;
  if (/github-actions\[bot\]/i.test(login)) return undefined; // GA bot, no marker → not review content
  if (/\[bot\]/i.test(login)) return login; // any other bot keeps its login
  return undefined; // humans excluded (matches the isBot filter)
}

const UNTRUSTED_DEFAULT: Omit<ReviewerProfile, "source"> = {
  trusted: false,
  maxChars: 600,
  maxLines: 8,
  bodyIsFindings: false,
};

/** The digest policy for a resolved source. Trusted reviewers are unbounded findings channels;
 *  everything else (including unknown sources) gets the untrusted chrome-defanging default. */
export function profileFor(source: string): ReviewerProfile {
  if (TRUSTED_REVIEWERS.has(source)) {
    return {
      source,
      trusted: true,
      maxChars: undefined, // unbounded — §11 D1
      maxLines: undefined,
      bodyIsFindings: true,
    };
  }
  return { source, ...UNTRUSTED_DEFAULT };
}
